# -*- coding: utf-8 -*-
"""hello file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_fm-X_mmhA7ObF2EVQP61hYiU4HcZoI
"""

A= "hello world"

print(A)

